### ISSUE TITLE
Add support for Log4j 2

### ISSUE THREAD

**Issue by korydraughn** [irods/irods_client_http_java#46]
Users of the library need a way to view debug information, messages, etc.

Log4j 2 seems appropriate for that. See https://logging.apache.org/log4j/2.x/.

**Comment by sam-i-am012** [comment]
Still need to add logging for the following:

- [ ] CollectionOperations
- [ ] DataObjectOperations
- [ ] InformationOperations
- [ ] ResourceOperations
- [ ] RuleOperations
- [ ] TicketOperations
- [ ] UserGroupOperations
- [ ] ZoneOperations

**Comment by korydraughn** [comment]
Adding logging to the tests is separate from this issue.

You've added support for log4j 2 so you can close this issue and open another one for the tests.

**Comment by sam-i-am012** [comment]
Ohh I see, ok sounds good. 
Created #60

**Comment by korydraughn** [comment]
Closing now that #60 was created.
