### ISSUE TITLE
README missing several important pieces of information

### ISSUE THREAD

**Issue by korydraughn** [irods/irods_client_http_java#87]
Please add the following:
- Brief description of the project
- Usage example showing:
  - Authentication
  - Execution of an operation
  - Error handling
  - Should include comments in the code snippet explaining what's happening

Look at the other HTTP API client repos to see what they are doing. The READMEs should be similar.

**Comment by sam-i-am012** [comment]
This issue also needs to be closed please

**Comment by trel** [comment]
Done!
